[env]
LIBTORCH_USE_PYTORCH = '1'

[build]
# rustflags = ["--cfg", "feature=\"pytorch\""]

[target.aarch64-apple-darwin]
rustflags = ["-C", "target-feature=+neon"]

[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "target-feature=+avx2", "-C", "target-feature=+fma"]

[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+avx2", "-C", "target-feature=+sse4.2"]
